### ISSUE TITLE
Can't login through cloud web app

### ISSUE THREAD

**Issue by bugs181** [airmessage/airmessage-web#5]
Cross posted from: https://www.reddit.com/r/AirMessage/comments/pn4oey/cant_login_through_cloud_web_app/

Tested on several devices, different browsers, all have unexpected behavior.
- Opening `web.airmessage.org` on Mac Safari (Same MacBook the Airmessage server is running) gives a blank page.
- Opening on Brave browser on iOS presents the page but after successfully signing in through Google, the page does not change. Tapping it again dos nothing.
- Opening on Safar on iOS has the same effect as above.

Server logs from: `~/Library/Application Support/AirMessage/logs/latest.log`

```
21-09-12 19:07:46 [WARNING] Unable to read process output: sysctl: unknown oid 'sysctl.proc_translated'
21-09-12 19:07:46 [INFO] Starting AirMessage Server version 3.3.2
21-09-12 19:07:46 [WARNING] Unable to read keychain value (service: AirMessage, account: airmessage-password): security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
21-09-12 19:07:46 [WARNING] Unable to read keychain value (service: AirMessage, account: airmessage-installation): security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
21-09-12 19:07:47 [INFO] Using time system MAC_ABSOLUTE_TIME with current time 1631491667940 -> 653184467940000000
21-09-12 19:07:49 [INFO] Started Connect account server on port 53264
21-09-12 19:09:35 [INFO] Stopped Connect account server
21-09-12 19:09:36 [INFO] Connection to Connect relay opened
21-09-12 19:09:36 [WARNING] null
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
	at me.tagavari.airmessageserver.connection.DataProxy.notifyStart(DataProxy.java:61)
	at me.tagavari.airmessageserver.connection.connect.DataProxyConnect.processData(DataProxyConnect.java:244)
	at me.tagavari.airmessageserver.connection.connect.ConnectWebSocketClient.onMessage(ConnectWebSocketClient.java:99)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
	at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:936)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:889)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.base/java.lang.Thread.run(Unknown Source)
21-09-12 19:09:50 [FINEST] Updated chat creation target index
```

**Comment by bugs181** [comment]
Solution: Use a different web browser. Seems to be an issue with ad blocking.
